/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gestore_attivita.gestore_attivita.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AttivitaListSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 976864931175790988L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AttivitaListSchema\",\"namespace\":\"it.gestore_attivita.gestore_attivita.kafka.avro\",\"fields\":[{\"name\":\"attivitas\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AttivitaRequestGenerated\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"alias\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"lavorata\",\"type\":\"boolean\"},{\"name\":\"attivitaPadre\",\"type\":[\"null\",\"long\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AttivitaListSchema> ENCODER =
      new BinaryMessageEncoder<AttivitaListSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AttivitaListSchema> DECODER =
      new BinaryMessageDecoder<AttivitaListSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AttivitaListSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AttivitaListSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AttivitaListSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AttivitaListSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AttivitaListSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AttivitaListSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AttivitaListSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AttivitaListSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> attivitas;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AttivitaListSchema() {}

  /**
   * All-args constructor.
   * @param attivitas The new value for attivitas
   */
  public AttivitaListSchema(java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> attivitas) {
    this.attivitas = attivitas;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attivitas;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attivitas = (java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attivitas' field.
   * @return The value of the 'attivitas' field.
   */
  public java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> getAttivitas() {
    return attivitas;
  }


  /**
   * Sets the value of the 'attivitas' field.
   * @param value the value to set.
   */
  public void setAttivitas(java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> value) {
    this.attivitas = value;
  }

  /**
   * Creates a new AttivitaListSchema RecordBuilder.
   * @return A new AttivitaListSchema RecordBuilder
   */
  public static it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder newBuilder() {
    return new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder();
  }

  /**
   * Creates a new AttivitaListSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AttivitaListSchema RecordBuilder
   */
  public static it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder newBuilder(it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder other) {
    if (other == null) {
      return new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder();
    } else {
      return new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder(other);
    }
  }

  /**
   * Creates a new AttivitaListSchema RecordBuilder by copying an existing AttivitaListSchema instance.
   * @param other The existing instance to copy.
   * @return A new AttivitaListSchema RecordBuilder
   */
  public static it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder newBuilder(it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema other) {
    if (other == null) {
      return new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder();
    } else {
      return new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for AttivitaListSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AttivitaListSchema>
    implements org.apache.avro.data.RecordBuilder<AttivitaListSchema> {

    private java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> attivitas;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attivitas)) {
        this.attivitas = data().deepCopy(fields()[0].schema(), other.attivitas);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AttivitaListSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.attivitas)) {
        this.attivitas = data().deepCopy(fields()[0].schema(), other.attivitas);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'attivitas' field.
      * @return The value.
      */
    public java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> getAttivitas() {
      return attivitas;
    }


    /**
      * Sets the value of the 'attivitas' field.
      * @param value The value of 'attivitas'.
      * @return This builder.
      */
    public it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder setAttivitas(java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> value) {
      validate(fields()[0], value);
      this.attivitas = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attivitas' field has been set.
      * @return True if the 'attivitas' field has been set, false otherwise.
      */
    public boolean hasAttivitas() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attivitas' field.
      * @return This builder.
      */
    public it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaListSchema.Builder clearAttivitas() {
      attivitas = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AttivitaListSchema build() {
      try {
        AttivitaListSchema record = new AttivitaListSchema();
        record.attivitas = fieldSetFlags()[0] ? this.attivitas : (java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AttivitaListSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<AttivitaListSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AttivitaListSchema>
    READER$ = (org.apache.avro.io.DatumReader<AttivitaListSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.attivitas.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated e0: this.attivitas) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> a0 = this.attivitas;
      if (a0 == null) {
        a0 = new SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>((int)size0, SCHEMA$.getField("attivitas").schema());
        this.attivitas = a0;
      } else a0.clear();
      SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> a0 = this.attivitas;
          if (a0 == null) {
            a0 = new SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>((int)size0, SCHEMA$.getField("attivitas").schema());
            this.attivitas = a0;
          } else a0.clear();
          SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new it.gestore_attivita.gestore_attivita.kafka.avro.AttivitaRequestGenerated();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










